# Generated by Django 2.2.3 on 2019-08-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientName',
            fields=[
                ('ingredient_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '성분이름',
                'verbose_name_plural': '성분이름',
                'db_table': 'ingredient_name',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=0, verbose_name='성분함량')),
                ('detail_content', models.TextField(default='', verbose_name='성분상세내용')),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.IngredientName', verbose_name='성분이름')),
            ],
            options={
                'verbose_name': '성분',
                'verbose_name_plural': '성분',
                'db_table': 'ingredient',
            },
        ),
    ]
