# Generated by Django 2.2.3 on 2019-08-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_class', models.CharField(max_length=50, verbose_name='성분분류')),
            ],
            options={
                'verbose_name': '성분분류',
                'verbose_name_plural': '성분분류',
                'db_table': 'ingredient_class',
            },
        ),
        migrations.CreateModel(
            name='Ingredient_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=80, verbose_name='성분이름')),
            ],
            options={
                'verbose_name': '성분이름',
                'verbose_name_plural': '성분이름',
                'db_table': 'ingredient_name',
            },
        ),
        migrations.CreateModel(
            name='Ingredient_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_unit', models.CharField(max_length=10, verbose_name='성분단위')),
            ],
            options={
                'verbose_name': '성분단위',
                'verbose_name_plural': '성분단위',
                'db_table': 'ingredient_unit',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_detail_content', models.TextField(blank=True, verbose_name='성분상세내용')),
                ('ingredient_volume', models.IntegerField(default=0, verbose_name='성분함량')),
                ('ingredient_class', models.ForeignKey(default='null', on_delete=django.db.models.deletion.PROTECT, to='ingredient.Ingredient_class')),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient_name')),
                ('ingredient_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredient.Ingredient_unit')),
            ],
            options={
                'verbose_name': '성분',
                'verbose_name_plural': '성분',
                'db_table': 'ingredient',
            },
        ),
    ]
