# Generated by Django 2.2.3 on 2019-08-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='detail_content',
            field=models.TextField(blank=True, verbose_name='성분상세내용'),
        ),
    ]
