# Generated by Django 2.2.4 on 2019-08-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_class_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.PROTECT, to='ingredient.Ingredient_class', verbose_name='성분 분류'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient_name', verbose_name='성분 이름'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_unit_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.PROTECT, to='ingredient.Ingredient_unit', verbose_name='성분 단위'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_volume',
            field=models.PositiveIntegerField(default=0, verbose_name='성분 함량'),
        ),
        migrations.AlterField(
            model_name='ingredient_unit',
            name='ingredient_unit_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='성분 단위'),
        ),
    ]
