# Generated by Django 2.2.4 on 2019-08-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20190803_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=80, verbose_name='성분이름')),
                ('ingredient_class', models.CharField(max_length=80, verbose_name='성분분류')),
            ],
            options={
                'verbose_name': '성분이름',
                'verbose_name_plural': '성분이름',
                'db_table': 'ingredient_name',
            },
        ),
        migrations.CreateModel(
            name='Ingredient_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_unit', models.CharField(max_length=10, verbose_name='성분단위')),
            ],
            options={
                'verbose_name': '성분단위',
                'verbose_name_plural': '성분단위',
                'db_table': 'ingredient_unit',
            },
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='detail_content',
            new_name='ingredient_detail_content',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='volume',
            new_name='ingredient_volume',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient_name'),
        ),
        migrations.DeleteModel(
            name='IngredientName',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_unit',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.PROTECT, to='ingredient.Ingredient_unit'),
            preserve_default=False,
        ),
    ]
