# Generated by Django 2.2.4 on 2019-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('effect_id', models.AutoField(primary_key=True, serialize=False)),
                ('effect_name', models.CharField(max_length=32, verbose_name='약 효능')),
            ],
            options={
                'verbose_name': '약 효능',
                'verbose_name_plural': '약 효능',
                'db_table': 'effect',
            },
        ),
    ]
